[package]
name = "rps-ios"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rps_ios"
crate-type = ["staticlib", "cdylib"]

[dependencies]
rps-core = { path = "../rps-core" }
